### ISSUE TITLE
Legality of Loan

### ISSUE THREAD

**Issue by wimanesti** [enabledao/enable#18]
I have some questions/concerns regarding the loan:
1. Who forces the smart contract if either party breaches the contract?
2. What if the stable coin we use closes down? How do I repay?
3. What if the stable coin I use is no longer 1:1 ratio, lets say it changes to 1 coin for 1000 dollar or the other way around? How to mitigate or how to make sure it's fair for both parties in case changes happen
 4. Is it possible that one of the lenders force me to early repay the full amount I owe them before the loan due?
5. To what extent I have to share my personal data? What will they know about me and how can I be sure it's safe and not misused

**Comment by adibas03** [comment]
This are very important questions.
Some of the questions can be delayed to be answered down the line, as we approach actual product design, since this is just an MVP.
> Who forces the smart contract if either party breaches the contract?
- Mostly, this has to be handled offchain, probably making an agreement with Bloom to disable the defaulting party's account or something along those lines.  
> What if the stable coin we use closes down? How do I repay?
- This odds of this can be minimized by our multi-coin payment model, where you can set more than one paying contract. Although the chance still exists of anything going wrong. In which case, we can have a function to change the payment token address, which is restricted by some level of consensus: say both borrower and at least 75% of lenders approve change.
> What if the stable coin I use is no longer 1:1 ratio, lets say it changes to 1 coin for 1000 dollar or the other way around? How to mitigate or how to make sure it's fair for both parties in case changes happen
- This is handled by the above scenario  
> Is it possible that one of the lenders force me to early repay the full amount I owe them before the loan due?
- For this Iteration, it is not possible, and this should be discussed further to consider if it is at all economically sensible.
> To what extent I have to share my personal data? What will they know about me and how can I be sure it's safe and not misused
- We need to discuss further on this, but looking at security, securities and the present practices in the world, the borrower can not have an secrets from the lenders, concerning the Loan, or they are liable.

Hope I was able to answer the questions.
@onggunhao @tspoff  Do you have any thoughts on this?

**Comment by wimanesti** [comment]
Thanks for the information @adibas03 . I will ask a lot more questions since this is a new thing I'm not familiar with, so please bear with me :)

I have follow up questions on this

> What if the stable coin I use is no longer 1:1 ratio, lets say it changes to 1 coin for 1000 dollar or the other way around? How to mitigate or how to make sure it's fair for both parties in case changes happen

> This is handled by the above scenario

1. What if it doesn't reach 75% consensus for a period of time that it passes monthly due?
2. What if I can't repay because the stablecoin is not 1:1 anymore to the point where my total loan and monthly repayment are way above my ability to pay?

Thanks!

**Comment by adibas03** [comment]
> What if it doesn't reach 75% consensus for a period of time that it passes monthly due?
- The 75% is actually an arbitrary value, it would be tinkered with to get a sweet spot. To answer the core question which is *what happens if there is no consensus to alter the address*.
Sincerely, I can't say that I know, but these are the type of things we learn along the line.
> What if I can't repay because any stablecoin is not 1:1 anymore to the point where my total loan and monthly repayment are way beyond my ability to pay?
- So, the system will be built to penalize bad behavior (probably later versions). So, although we do not want to repeat the failing model of loan interests in the real world, which make it impossible to repay debts, due to the interest once one or a few are missed, we still need to dis-incentivize bad actors. Now, how we are going to achieve this, also falls under what we find out as we build out the product.

Glad to be of help

**Comment by onggunhao** [comment]
My 2 cents (also spoke with Ines in person)

1. For stablecoins not being 1:1 means a failure of a particular stablecoin (e.g. Tether trading at 0.98 : 1 USD for now). In most cases, lenders are the ones that have highest risk

2. For changing of token address - I wonder how we will continue to keep track of units (i.e. you just need to send 700 units of whatever ERC20 is in the future). This seems dangerous to write into a smart contract.

For example, a cartel of lenders would be incentivized to switch the payment token to a tokenized BTC, which is definitely not 1 USD.

3. For MVP, I think we should optimize for simplicity. Having 2-3 stablecoins (USDC, Paxos, Dai) written into a 10 year loan agreement might be a compromise - two relatively trusted and well funded operations, and a decentralized Dai.

**Comment by onggunhao** [comment]
I'm keeping this issue open as I think we need to think through:

- [ ] What warnings should we put up about using Enable? (i.e. similar to Uniswap, i.e. tell them that they are using beta software)
- [ ] What disclaimers should we put about the loan parameters? We should be upfront and honest and tell them that they do not have any of the typical legal recourses that debt contracts have
- [ ] Cryptocurrencies are regulated as commodities in Indonesia. Are there any laws regarding the loan of cryptocurrencies? Does Ines even count as an Indonesian resident for the purposes of this project?
- [ ] Which jurisdiction is this governed by? Magic internet money?

**Comment by onggunhao** [comment]
Some inspirations from Gnosis' Wallet:

![image](https://user-images.githubusercontent.com/518024/58099876-d2225e00-7bdc-11e9-85c1-96b4ba1af8f4.png)

**Comment by onggunhao** [comment]
Archiving thread
