### ISSUE TITLE
Borrower should be able to deploy a loan request with amortization table

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable#8]
### Spec 

**Step 1: Borrower deploys Loan Request**
Borrower should be able to deploy a Loan Contract, which defaults to the initial state of "New Request". The borrower will specify loan request params, which are the following:

- principal amount
- disbursement date
- disbursement address
- effective interest rate
- tenor
- grace period on principal
- grace period on interest

Step 2: Loan Request produces deterministic amortization schedule
Loan Proposal should have a call function that, based on proposed loan parameters, generates an amortization schedule (i.e. proposed repayment schedule). This removes the possibility for ambiguity (e.g. different rates)

### Things to decide

- [ ] Use Dharma debt request contract?
- [ ] Can Dharma debt contract produce an amortization table?
- [ ] Can Dharma debt contract accommodate a grace period of 24 months?
- [ ] Does Dharma debt contract produce a principal / interest / fees / penalties breakdown?

**Comment by adibas03** [comment]
I have a question on this, though it might not be feasible, or better still only lead to complications.
Will the accepted payment types be restricted to only one, or will different payment types be accepted.
So, Can the contract accept only USDC, or both USD and Paxos?
This has to be predetermined and set at contract creation.
Also, just to confirm, since it is ERC20 payment style, Funding action will have to be a two step process.
Lender approves the contract the amount of tokens intended to fund, then make the call to the contract, where the contract does the actual transfer. Or something along this lines.

**Comment by onggunhao** [comment]
Moved to https://github.com/enabledao/enable-contracts/issues/18
